### ISSUE TITLE
Doors not well named

### ISSUE THREAD

**Issue by IntelOrca** [kapdap/re-cvx-tools#1]
What is described as doors is actually any area that can trigger a door, item pickup, or message amongst other things. In the older games, these are referred to as AOTs.
Unknown2 seems to be the type, where 0 is door (with Unknown 12 being stage, Unknown13 being room), 4 is item (with Unknown 12 being the index into the item table). 3 is usually message (with Unknown 12 being message ID) but seems to also trigger some item pick ups as well.

Here are some of the things I am trying to wrap my head around:
* Some rooms that have an item pickup, do not have an associated item in the item table. For example the padlock key in 108 (Execution yard). It is possible the item table is only used where there is a visble model of the item.
* Many rooms have an item pickup which is in the item table, but changing the type in the table does not affect what is picked up. For example the handgun ammo on the bookshelf in 106 (Barracks), or the hawk emblem in 104 (Computer room), or any item in 10A (Iron bridge).
* 102 (Graveyard) and 103 (Yard) have two files for the room, not sure what the difference between them are. 103 maybe before and after the zombies are spawned, although I have not successfully been able to change the briefcase or handgun ammo to another item.

**Update:**
I have started decoding the embedded script in the room file (flags should be renamed to script address). The script has the code for overriding certain items and pickups.

**Comment by kapdap** [comment]
[cbnj](https://www.dreamcast-talk.com/forum/memberlist.php?mode=viewprofile&u=16823) has discoved some of the script opcodes and posted them on the DC-Talk forum

https://www.dreamcast-talk.com/forum/viewtopic.php?f=52&t=16893#p180001

**Comment by IntelOrca** [comment]
Thanks, I have been talking to cbnj in the discord channel for CVX and uncovered most of my queries. My plan is to name all the remaning fields as best as I can.

If you are interested, this is what I am working on, a randomizer for CVX PS2. So far I have randomized the prison and palace.
https://github.com/IntelOrca/biorand

**Comment by kapdap** [comment]
Excellent, there have been a few requests for a CVX randomizer so it's nice to hear someone it working on it.

I've also updated the Blender plugin by @mortician to work with Blender 2.80+. Currently it imports room boundries and triggers areas as simple meshes. https://github.com/kapdap/lib_biocv

**Comment by kapdap** [comment]
@IntelOrca I found the jump table for the script functions and have dumped them here https://github.com/kapdap/re-cvx-tools/blob/master/Resources/Scripting.md.

Still need to figure out the argument list for each function. An accurate list can be made by steping through the code using IDA/Ghidra/PCSX2 Debugger. Most of the debug symbols are avaliable on the PS2 releases which makes things a little easier to work with.

**Comment by IntelOrca** [comment]
> @IntelOrca I found the jump table for the script functions and have dumped them here https://github.com/kapdap/re-cvx-tools/blob/master/Resources/Scripting.md.
> 
> Still need to figure out the argument list for each function. An accurate list can be made by steping through the code using IDA/Ghidra/PCSX2 Debugger. Most of the debug symbols are avaliable on the PS2 releases which makes things a little easier to work with.

This is incredibly helpful! Thank you so much for this. 🙂
