### ISSUE TITLE
Nice work.

### ISSUE THREAD

**Issue by krzys837** [kapdap/re-cvx-tools#2]
Hello.
I checked it qucikly.
Nice informations and work.

Let me know if you or someone has a questions about Code Veronica stuff
👍
Best regards.

**Comment by kapdap** [comment]
Hi @krzys837 

Thanks to your translation guide and @MaikelChan work I was able to easily decode the text messages
Next step will be to add tables to decode other languages (I saw SPA and EUR tables in your guide but I haven't included them for now)

Also thanks for your feedback it's appericated 👍
