### ISSUE TITLE
Gun Survivor 2 support

### ISSUE THREAD

**Issue by descawed** [kapdap/re-cvx-tools#3]
I've recently been digging into the files for Gun Survivor 2 (the Code Veronica arcade shooter spinoff), and I thought you might not be aware that it seems the RDX format is almost exactly the same between CV and Survivor 2. Other than some unknown or mixed up enemy/item names, your RDXplorer tool works perfectly with the Survivor 2 files. Better yet, it seems that at least the Japanese PS2 version of Survivor 2 contains debug symbols, so it could be a valuable resource for learning more about the files, which would likely also be applicable to CV.

If you're interested, I could work on a PR for some Survivor 2 stuff, at least the enemy/item enums. But either way, I thought this might be useful info.

**Comment by krzys837** [comment]
Hello. Well that's right. CV2 files are similar to CV1. One thing is that, It's a little difficult to manual browse in Hex Editor because there's a lot of repeat the same texture files

**Comment by descawed** [comment]
I see. I wasn't sure if you'd seen the CV2 files since I didn't see it mentioned in the code. I was most excited to find the debug symbols in the executable, which I'd hoped would help identify some of the unknown parts of the format, although I'm not sure if you've seen those as well or what your reverse engineering progress is. In any case, I would be interested in adding the additional enemy and item IDs once I identify them.

**Comment by descawed** [comment]
I'll close this issue since my PR was merged. I may submit another PR if I find anything else interesting, but no reason to have this sitting open until then.
